### ISSUE TITLE
Slice to end of source results in empty string

### ISSUE THREAD

**Issue by benmerckx** [haxetink/tink_parse#1]
Getting a slice that reaches the end of the source results in an empty string:

```haxe
var slice: StringSlice = 'abc';
trace(slice[0...2]); // 'ab'
trace(slice[0...3]); // ''
trace(slice[1...3]); // ''
```

As far as I can tell `start` and `end` (in `Data`) are off in these situations. They end up like this in the examples:
```haxe
slice[0...3]; // start: 0, end: 0
slice[1...3]; // start: 1, end: 1
```

**Comment by back2dos** [comment]
I'm going to reopen this though, since I think it should be properly specified and tested what happens in this particular edge case.

**Comment by back2dos** [comment]
Ok, this actually seems to behave intuitively now.
